#!/usr/bin/env bash
# Bash script that uses ssh to connect to my server using a private key ~/.ssh/school with the user ubuntu

# Use ssh with single-character flags to connect using the private key
ssh -i ~/.ssh/school ubuntu@18.208.221.15
