#!/usr/bin/env bash
# Bash script to configure Nginx with a custom
#+ HTTP response header on web-01 and web-02

# Update package list and install Nginx
sudo apt-get update -y
sudo apt-get install nginx -y

# Add the custom HTTP response header directly to the Nginx configuration file
echo "add_header X-Served-By \$hostname;" | sudo tee -a /etc/nginx/sites-available/default

# Restart Nginx to apply the changes
sudo service nginx restart

# Verify Nginx status
sudo service nginx status
