#!/usr/bin/env bash
# Installs Nginx with the following configurations:
# - Listens on port 80.
# - Returns a page containing "Holberton School" when queried at the root with a curl GET request.
# - Configures /redirect_me as a "301 Moved Permanently".
# - Includes a custom 404 page containing "Ceci n'est pas une page".

# Update package list and install Nginx
apt-get update
apt-get install -y nginx

# Create necessary directories and files for Nginx
mkdir -p /etc/nginx/html
touch /etc/nginx/html/index.html
echo "Hello World!" > /etc/nginx/html/index.html

touch /etc/nginx/html/404.html
echo "Ceci n'est pas une page" > /etc/nginx/html/404.html

# Configure Nginx
cat <<EOL > /etc/nginx/sites-available/default
server {
    listen 80;
    listen [::]:80 default_server;
    add_header X-Served-By \$HOSTNAME;

    root /etc/nginx/html;
    index index.html index.htm;

    location /redirect_me {
        return 301 http://cuberule.com/;
    }

    error_page 404 /404.html;
    location /404 {
        root /etc/nginx/html;
        internal;
    }
}
EOL

# Restart Nginx to apply the changes
service nginx restart
