#!/usr/bin/env bash
# Bash script that installs HAProxy & makes configurations

# Install required packages
apt-get -y install software-properties-common
add-apt-repository ppa:vbernat/haproxy-1.8
apt-get update
apt-get -y install haproxy

# Enable HAProxy
echo "ENABLED=1" >> /etc/default/haproxy

# Configure HAProxy
printf %s "listen 5452-webs
    bind *:80
    mode http
    balance roundrobin
    server 5487-web-01 54.226.182.255:80 check
    server 5780-web-02 52.200.5.159:80 check
" >> /etc/haproxy/haproxy.cfg

# Restart HAProxy service
sudo service haproxy restart
