#!/usr/bin/env bash
# Nginx must be running, and listening on port 80 of all the server
rm /etc/nginx/sites-enabled/default
ln -s /etc/nginx/sites-available/default /etc/nginx/sites-enabled/
curl -i  0:80
