#!/usr/bin/env bash
# Bash script to transfer a file to a server using scp

# Check if the correct number of parameters is provided
if [ "$#" -ne 4 ]; then
    echo "Usage: $0 PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
    exit 1
fi

# Assign parameters to variables
file_path="$1"
server_ip="$2"
username="$3"
ssh_key_path="$4"

# Transfer the file to the user's home directory on the server using scp
scp -o StrictHostKeyChecking=no -i "$ssh_key_path" "$file_path" "$username"@"$server_ip":~/

# Check if scp command was successful
if [ $? -eq 0 ]; then
    echo "File successfully transferred to the server!"
else
    echo "Error: File transfer failed."
fi
