#!/usr/bin/env bash
# Bash script configures an Nginx server so that /redirect_me redirects to another page.
# The redirection is configured as a "301 Moved Permanently"

apt-get update
apt-get install -y nginx

mkdir /etc/nginx/html
touch /etc/nginx/html/index.html
echo "Holberton School" > /etc/nginx/html/index.html
printf %s "server {
    listen 80;
    listen [::]:80 default_server;
    root   /etc/nginx/html;
    index  index.html index.htm;

    location / {
	try_files \$uri \$uri/ =404;
    }
    location /redirect_me {
        return 301 https://youtu.be/JKxlsvZXG7c?si=-8F7Ta5pxdxkYhTi;
    }
}" > /etc/nginx/sites-available/default

service nginx restart
